// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:app_flutter_produkt_bestellen/core/fix_values/flavor.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return AppConfig.appFlavor == Flavor.development
            ? androidDevelopment
            : androidProduction;
      case TargetPlatform.iOS:
        return AppConfig.appFlavor == Flavor.development
            ? iosDevelopment
            : iosProduction;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidDevelopment = FirebaseOptions(
    apiKey: 'AIzaSyA7Ot1z-ztfdOaWArD03RO27wfTXLt-GXY',
    appId: '1:723074710528:android:39800dfcf1fd4b87886ce5',
    messagingSenderId: '723074710528',
    projectId: 'appproduktebestellen',
    databaseURL:
        'https://appproduktebestellen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appproduktebestellen.appspot.com',
  );

  static const FirebaseOptions androidProduction = FirebaseOptions(
      apiKey: 'AIzaSyBqlZFQhGqIdLp7cB9jY6dj4KZyHfJo_x4',
      appId: '1:597853162277:android:06a1fda1f5491b25bd68cc',
      messagingSenderId: '597853162277',
      projectId: 'app-produkte-bestellen-prod',
      storageBucket: 'app-produkte-bestellen-prod.appspot.com');

  static const FirebaseOptions iosDevelopment = FirebaseOptions(
    apiKey: 'AIzaSyCVFp1g2vP2aysijJts9ekpjmRFtp0bFcc',
    appId: '1:723074710528:ios:67526495bfb89713886ce5',
    messagingSenderId: '723074710528',
    projectId: 'appproduktebestellen',
    databaseURL:
        'https://appproduktebestellen-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'appproduktebestellen.appspot.com',
    iosBundleId: 'com.example.appFlutterProduktBestellen',
  );

  static const FirebaseOptions iosProduction = FirebaseOptions(
    apiKey: 'AIzaSyDc8sDuL1xGyCyJwy7nCfhzCmCPCm1HN8I',
    appId: '1:597853162277:ios:97e862c5b0062a1fbd68cc',
    messagingSenderId: '597853162277',
    projectId: 'app-produkte-bestellen-prod',
    storageBucket: 'app-produkte-bestellen-prod.appspot.com',
    iosBundleId: 'com.example.appFlutterProduktBestellen.prod',
  );
}
