name: "build release on pull request"
#pipline
on:
  pull_request:
    branches:
      - master
      - main
      - develop
    types: [ opened, synchronize, reopened ]

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
          - development
          - production
        build-type:
          - release
          - develop

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Empfohlene Distribution für Java
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Import Keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE" | base64 --decode > /tmp/keystore.jks
          echo "flutter.buildModes.release.signingConfigs.release.keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "flutter.buildModes.release.signingConfigs.release.storeFile=/tmp/keystore.jks" >> android/key.properties
          echo "flutter.buildModes.release.signingConfigs.release.storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "flutter.buildModes.release.signingConfigs.release.keyPassword=$KEY_PASSWORD" >> android/key.properties
      - run: rm -f pubspec.lock
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test


  ios_develop:
    name: Build Flutter (iOS - Debug)
    needs: [ flutter_test ]
    runs-on: macos-latest
    strategy:
      matrix:
        flavor:
          - development
          - production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Empfohlene Distribution für Java
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --flavor ${{ matrix.flavor }} --debug --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.flavor }}-ios-develop
          path: build/ios/ipa/*.ipa

  ios_release:
    name: Build Flutter (iOS - Release)
    needs: [ flutter_test ]
    runs-on: macos-latest
    strategy:
      matrix:
        flavor:
          - development
          - production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Empfohlene Distribution für Java
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --flavor ${{ matrix.flavor }} --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.flavor }}-ios-release
          path: build/ios/ipa/*.ipa

  android_develop:
    name: Build Flutter (Android - Debug)
    needs: [ flutter_test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
          - development
          - production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Empfohlene Distribution für Java
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --flavor ${{ matrix.flavor }} --debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.flavor }}-android-develop
          path: build/app/outputs/flutter-apk/*.apk


  android_release:
    name: Build Flutter (Android - release)
    needs: [ flutter_test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor:
          - development
          - production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Empfohlene Distribution für Java
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --flavor ${{ matrix.flavor }} --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.flavor }}-android-release
          path: build/app/outputs/flutter-apk/*.apk



