name: "build release on pull request"

on:
  pull_request:
    branches:
      - main
      - master
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Empfohlene Distribution für Java
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - run: rm -f pubspec.lock
      - run: flutter clean
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release --verbose
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}